stages:          # List of stages for jobs, and their order of execution
  - test

e2e-test-android:   # This job runs in the test stage.
  rules:
    - changes:
        - 'README.md'
        - 'images/**/*'
        - '.docs/**/*'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "develop")'
      when: always
    - changes:
        - '**/*'
      if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop")'
      when: always

  stage: test    # It only starts when the job in the build stage completes successfully.

  image: docker:git
  variables:
    TESTIM_DOCKER: testim/docker-cli
    TESTIM_GRID: GroupB-agruber
    TESTIM_LABEL: GroupB
  services:
    - docker:stable-dind
  script:
    - docker pull $TESTIM_DOCKER
    - ls -la $(pwd)
    - docker run --rm -v "$(pwd)":/opt/testim-runner $TESTIM_DOCKER --token "$TESTIM_TOKEN" --project "$TESTIM_PROJECT" --grid "$TESTIM_GRID" --label "$TESTIM_LABEL" --mode appium -c /opt/testim-runner/testimConfig.js -r /opt/testim-runner/testim-report.xml
  artifacts:
    paths:
      - testim-report.xml
    reports:
      junit: testim-report.xml
