name: Run testim e2e tests for Android  

on:
  push:
    branches: [ "main", "release/*", "develop", "develop/*" ]
    paths-ignore:
      - '.docs/**'
      - 'images/**'
      - 'README.md'
  pull_request:
    branches: [ "main", "release/*", "develop", "develop/*" ]
    paths-ignore:
      - '.docs/**'
      - 'images/**'
      - 'README.md'
  release:
    types: [published]

jobs:
  e2e-test-android:
    runs-on: ubuntu-latest
    env:
      TESTIM_TOKEN: ${{ secrets.TESTIM_TOKEN }}
      TESTIM_PROJECT: ${{ vars.TESTIM_PROJECT }}
      TESTIM_GRID: GroupB-agruber
      TESTIM_LABEL: GroupB
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - run: npm install -g @testim/testim-cli
      - run: |
          testim --token "$TESTIM_TOKEN" --project "$TESTIM_PROJECT" --grid "$TESTIM_GRID" --label "$TESTIM_LABEL" --mode appium -c testimConfig.js -r testim-report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'testim-report.xml'
